name: 02 - Workflow Events
on:
  workflow_dispatch:
    inputs:
      message:
        description: "The message to commit"
        required: true
        default: "Hello, world!"
  schedule:
    - cron: "0 0 * * *"
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "The event that triggered this build was ${{ github.event_name }}."